[build]
publish = "./exampleSite/public/"
command = "npm run deploy"
[build.environment]
HUGO_VERSION = "0.139.4"
NODE_VERSION = "18"
HUGO_ENV = "production"
GO_VERSION = "1.23"
NODE_ENV = "development"
